---
title: "Group 20"
format: 
  html:
    embed-resources: true
    code-tools: true
  pdf: default
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  eval: true
  warning: false
  message: false
---

```{r}
library(dplyr)
library(ggplot2)
library(faraway)
library(gridExtra)
library(MASS)
library(plyr)
library(dplyr)
library(sjPlot)
library(nnet)
library(caret)
library(pROC)
library(tidymodels)
```

## GLM Analysis for Outcome Type

### Data Preparation

```{r}
data <- read.csv('dataset20.csv', stringsAsFactors = FALSE)
str(data)

data$animal_type <- as.factor(data$animal_type)
data$intake_type <- as.factor(data$intake_type)
data$outcome_type <- as.factor(data$outcome_type)
data$chip_status <- as.factor(data$chip_status)
```

### Explanatory Data Analysis

#### outcome_type

```{r}
unique(data$outcome_type)

ggplot(data, aes(x=outcome_type, y=time_at_shelter, group=outcome_type))+
  geom_boxplot(aes(fill=outcome_type))

ggplot(data, aes(x=time_at_shelter, fill=chip_status))+
  geom_boxplot(aes(y=outcome_type))

ggplot(data, aes(x=time_at_shelter, fill=animal_type))+
  geom_boxplot(aes(y=outcome_type))
```

#### time_at_shelter

```{r}
ggplot(data, aes(x=time_at_shelter))+
geom_boxplot()
# outliers: replace
Q1 <- quantile(data$time_at_shelter, 0.25)
Q3 <- quantile(data$time_at_shelter, 0.75)
IQR <- Q3 - Q1
upper <- Q3 + 1.5 * IQR
out <- which(data$time_at_shelter > upper)
med <- median(data$time_at_shelter)
data$time_at_shelter[out] <- med
ggplot(data, aes(x=time_at_shelter)) + 
  geom_histogram(binwidth=1, fill='blue', color='black')
```

#### animal_type

```{r}
# animal_type
prop.table(table(data$animal_type))
# think twice
data <- data %>%
  filter(!(animal_type=="BIRD" | animal_type=="WILDLIFE"))
```

#### month

```{r}
ggplot(data, aes(x = month)) +
  geom_bar(aes(fill = outcome_type), position = "dodge") +
  facet_wrap(~outcome_type)
```

#### year

```{r}
ggplot(data, aes(x = year)) +
  geom_bar(aes(fill = outcome_type), position = "dodge") +
  facet_wrap(~outcome_type)
```

### Model Fitting

#### Multinomial logistic regression model

```{r}
set.seed(1)
dim(data)
n <- nrow(data)

ind1 <- sample(c(1:n),round(n/2))
ind2 <- sample(c(1:n)[-ind1],round(n/4))
ind3 <- setdiff(c(1:n),c(ind1,ind2))
train.data <- data[ind1, ]
valid.data <- data[ind2, ]
test.data <- data[ind3, ]

dim(train.data)
dim(valid.data)
dim(test.data)
```

```{r}
# It seems there's no Multinomial logistic regression model in glm function
# I used multinom in package 'nnet' instead
glm_mult <- multinom(outcome_type ~ ., data = train.data)
summary(glm_mult)
# NaNs
```

#### Predict

```{r}
pred <- predict(glm_mult, newdata = test.data, type = "class")
confusionMatrix(table(pred, test.data$outcome_type))
```

```{r}
test.probs <- predict(glm_mult, newdata = test.data, type = "probs")
rocc <- roc(response = test.data$outcome_type, predictor = test.probs[,2])
plot(rocc)
auc(rocc)
# Roc seems weird
```

```{r}
test.data$pred <- pred
str(test.data)
accuracy(test.data, outcome_type, pred)
mcc(test.data, outcome_type, pred)
```
